spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5433/helden
    username: helden
    password: helden
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true

  sql:
    init:
      mode: always

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: false
    pool:
      enabled: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always